# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf18eb11a64578908319373983dc1355de948e5ce307f00156b3261c10007bbfa91bf41d0b52a90b811a07cf4f187ec80b9ecd45c375bc6e68443a6220a5bd5

test:
  secret_key_base: c361e55e16e64baae31c5be5d2fb0cfcf00f75e9f49e93b504a773d9465f05cf538358ee05e93eee502ed78bced981efa8c746f55721dba84435a27c06c2af37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
